"""British military-style operation code name generator.

Styles:
  modern   - single obscure word, MOD style (cf. Op TELIC, HERRICK, SHADER)
  ww2      - evocative words, English racecourses & hunts (cf. GOODWOOD, EPSOM),
             occasionally two-word (cf. MARKET GARDEN)
  exercise - adjective + noun training exercise (cf. Ex CAMBRIAN PATROL)

Real, well-known operation names are excluded so you don't clash with history.

CLI:  uv run opnames [-s modern|ww2|exercise] [-n COUNT] [--seed N]
"""
from __future__ import annotations

import argparse
import random
from dataclasses import dataclass, asdict

# Real operations/exercises to avoid (non-exhaustive).
REAL = {
    "TELIC", "HERRICK", "SHADER", "BANNER", "GRANBY", "CORPORATE", "ELLAMY",
    "PITTING", "TORAL", "KIPION", "TOSCA", "CABRIT", "NEWCOMBE", "TRENTON",
    "ORBITAL", "INTERFLEX", "GRITROCK", "RESCRIPT", "PALLISER", "FINGAL",
    "VERITAS", "RUMAN", "OVERLORD", "GOODWOOD", "EPSOM", "CHARNWOOD",
    "JUPITER", "BLUECOAT", "MARKET GARDEN", "VERITABLE", "PLUNDER", "CHASTISE",
    "JUBILEE", "TORCH", "HUSKY", "CRUSADER", "BATTLEAXE", "COMPASS",
    "LIGHTFOOT", "SUPERCHARGE", "DYNAMO", "SEALION", "BLACKCOCK", "VARSITY",
    "ANVIL", "SLEDGEHAMMER", "GAUNTLET", "HARPOON", "CLAYMORE", "AVALANCHE",
    "CATAPULT", "HURRICANE", "GROUSE", "PEDESTAL", "BAYTOWN", "BREVITY",
    "CAMBRIAN PATROL", "STEADFAST DEFENDER", "JOINT WARRIOR", "IRON SURGE",
    "WESSEX STORM", "SWIFT RESPONSE", "SPRING STORM", "IRON WOLF",
    "COLD RESPONSE", "TRIDENT JUNCTURE", "SAIF SAREEA", "GRIFFIN STRIKE",
}


def _words(text: str) -> list[str]:
    """Split a block of words, de-duplicate, and drop real op names."""
    return sorted(set(text.split()) - REAL)


# Obscure/archaic words: heraldry, fortification, arms & armour, seafaring,
# landscape, geology, birds, plants, cloth, tools and stars - the flavour of
# modern MOD nicknames.
MODERN = _words("""
ARGENT AZURE GULES SABLE VERT PURPURE TENNE SANGUINE ERMINE VAIR PALL PALE
BEND CHEVRON FESSE SALTIRE BORDURE CANTON GYRON LOZENGE MASCLE FUSIL ROUNDEL
BEZANT ANNULET MULLET ESTOILE CRESCENT MARTLET TORSE MANTLING BLAZON TINCTURE
RAMPANT PASSANT COUCHANT SEJANT STATANT GARDANT DORMANT VOLANT ENFIELD
GRIFFIN COCKATRICE CATAMOUNT WYVERN JESSANT TREFOIL
BARBICAN BASTION BATTLEMENT BERM BLOCKHOUSE CASEMATE CITADEL COUNTERSCARP
DEMILUNE DONJON ESCARP FASCINE FLECHE GLACIS HORNWORK LUNETTE MACHICOLATION
MOTTE BAILEY PALISADE PARADOS PARAPET POSTERN RAVELIN REDAN REDOUBT SALLYPORT
SANGAR TENAILLE TERREPLEIN TRAVERSE ABATIS BARTIZAN BRATTICE CRENEL MERLON
EMBRASURE GABION PORTCULLIS MANTLET PAVISE
ARMET BASINET BESAGEW BEVOR BRASSARD BRIGANDINE COIF COUTER CUISSE CUIRASS
GAMBESON GORGET GREAVE HAUBERK JUPON PAULDRON POLEYN SABATON SALLET SURCOAT
TASSET VAMBRACE AVENTAIL BURGONET MORION BALDRIC TABARD JERKIN QUILLON
ARBALEST BARDICHE BILLHOOK BODKIN CULVERIN DIRK FALCHION FAUCHARD GLAIVE
HALBERD HANGER LOCHABER MANGONEL ONAGER PARTISAN PETARD POLEAXE QUARREL
RANSEUR SAKER SPONTOON TREBUCHET VOULGE BALLISTA SPRINGALD CARRONADE FALCONET
SERPENTINE BOMBARD CALTROP SCABBARD FLINTLOCK PENNON
BINNACLE BOLLARD BOWSPRIT CAPSTAN CATHEAD CLEAT COAMING CRINGLE DAVIT DEADEYE
FAIRLEAD FATHOM FID FORECASTLE FOREMAST GUNWALE HALYARD HAWSER JIBBOOM KEDGE
KEELSON LANYARD LEEBOARD MARLINSPIKE MIZZEN OAKUM ORLOP PELORUS QUARTERDECK
RATLINE SCUPPER SHEAVE SHROUD SPANKER SPRIT STANCHION STAYSAIL TAFFRAIL
THOLE TOPGALLANT TOPSAIL TRANSOM WINDLASS YARDARM BOATSWAIN COXSWAIN
BRIGANTINE CARRACK CARAVEL CUTTER GALLEON KETCH LUGGER PINNACE SLOOP SCHOONER
YAWL CORACLE JACKSTAY SPINNAKER SEXTANT GIMBAL MARLIN NEAP
ARETE BOTHY BOURN BRAE BRECK BURN CARR CLEUGH CLINT COMBE CORRIE CRAG DENE
DINGLE DRUMLIN ESKER FELL FIRTH GILL GRIKE HAGG HOLM HOLT HOWE KAME KNAP
KNOLL LINN LOCHAN MERE NESS PELE RIGG SCAR SCREE SHAW SIKE SKERRY STRATH
SWALLET TARN THWAITE TOR WOLD WYKE COOMBE HEUGH CARSE MACHAIR SHINGLE
FELLSIDE HOLLOWAY LYNCHET MERESTONE SHIELING WEALD WHIN CAIRN BRACKEN
SHALE FLINT CHERT GNEISS GABBRO SCHIST FELDSPAR QUARTZ JASPER AGATE ONYX
GARNET BERYL OBSIDIAN CINNABAR GALENA MALACHITE PUMICE CORUNDUM PORPHYRY
TUFA MARL LOESS BASALT ASHLAR OCHRE UMBER QUOIN
AVOCET BITTERN BRAMBLING CHOUGH CORNCRAKE CROSSBILL CURLEW DOTTEREL DUNLIN
DUNNOCK FIELDFARE FIRECREST GADWALL GARGANEY GODWIT GOSHAWK GREENSHANK
GUILLEMOT KNOT LINNET MERGANSER NIGHTJAR NUTHATCH OUZEL PETREL PIPIT
REDSTART REDWING SANDERLING SCAUP SCOTER SHAG SHELDUCK SISKIN SKUA SMEW STINT
STONECHAT TURNSTONE TWITE WAGTAIL WHEATEAR WHIMBREL WHINCHAT YELLOWHAMMER
ALDER ASPEN BETONY BISTORT BRYONY BURDOCK CAMPION CELANDINE COWSLIP DITTANY
DOGWOOD EYEBRIGHT FEVERFEW FIGWORT FUMITORY GORSE HAWTHORN HELLEBORE HENBANE
HORNBEAM JUNIPER LOVAGE MADDER MALLOW MARJORAM MEADOWSWEET MUGWORT MULLEIN
ORPINE OXLIP PENNYROYAL PIMPERNEL ROWAN SAINFOIN SANICLE SAXIFRAGE SORREL
SPEEDWELL SPURGE STITCHWORT TANSY TEASEL TORMENTIL VERVAIN VETCH WOAD
WOODRUFF YARROW BLACKTHORN SLOE
ABEYANCE ALACRITY ANCHORITE APOGEE ARCANUM ARGOSY ASTROLABE AUGURY BALEFIRE
BELLWETHER BRUMAL CANTRIP CARILLON CATAPHRACT CHANTRY CIRCLET CLARION
COLLOQUY CORONACH CRUCIBLE CYNOSURE ECLIPTIC EMPYREAN EQUINOX FIRMAMENT
GALLIARD GLOAMING GNOMON GONFALON HALCYON HAUTBOY INGOT ISINGLASS LEVIN
MARGRAVE MERIDIAN NOCTURNE OBELISK ORIFLAMME PALADIN PALIMPSEST PARALLAX
PERIHELION PHAROS PLEIAD QUADRANT QUIETUS ROSTRUM SACKBUT SALIENT SARABAND
SENESCHAL SOLSTICE TALISMAN TAMBOUR TESSERA TOCSIN TRIPTYCH UMBRA VESPER
WASSAIL ZENITH ANABASIS AUSPEX CATENA NIMBUS ORRERY PIBROCH LODESTAR
AMBIT ABRADE GAMBIT FULCRUM TORQUE CLERESTORY CORBEL LINTEL VELLUM TALLOW
SPINDRIFT WAYMARK INGLE
BAIZE BOMBAZINE BROCADE BUCKRAM CALICO CAMBRIC DAMASK DIMITY FUSTIAN
GROSGRAIN HESSIAN KERSEY LINSEY MOLESKIN MUSLIN NANKEEN ORGANDIE PERCALE
POPLIN SATEEN SERGE SHALLOON TAFFETA TARLATAN TICKING TWILL WORSTED
ADZE AUGER BRADAWL DRAWKNIFE GIMLET HACKLE MATTOCK RASP SPOKESHAVE WHETSTONE
FETLOCK
ALDEBARAN ALTAIR ANTARES ARCTURUS BETELGEUSE CAPELLA CASTOR DENEB FOMALHAUT
MIRA POLARIS POLLUX PROCYON REGULUS RIGEL SIRIUS SPICA VEGA ACHERNAR CANOPUS
MIZAR ALCOR ALGOL BELLATRIX ELNATH
""")

# Racecourses, hunts, rivers, game birds, fish, dogs, weather and weapons -
# Normandy-era naming flavour (GOODWOOD, EPSOM and CHARNWOOD were racecourses).
WW2 = _words("""
AINTREE ASCOT CARTMEL CATTERICK CHEPSTOW DONCASTER EXETER FAKENHAM FONTWELL
HAYDOCK HEXHAM KELSO LUDLOW NEWBURY PLUMPTON REDCAR RIPON SEDGEFIELD THIRSK
TOWCESTER UTTOXETER WETHERBY WINCANTON AYR BANGOR BATH BEVERLEY BRIGHTON
CARLISLE CHELTENHAM FOLKESTONE HAMILTON HEREFORD HUNTINGDON KEMPTON LEICESTER
LINGFIELD MUSSELBURGH NEWCASTLE NEWMARKET NOTTINGHAM PERTH PONTEFRACT
SALISBURY SANDOWN SOUTHWELL STRATFORD TAUNTON WARWICK WINDSOR WOLVERHAMPTON
WORCESTER YORK
BELVOIR QUORN PYTCHLEY COTTESMORE FERNIE ZETLAND BRAMHAM BILSDALE CLEVELAND
HURWORTH TYNEDALE ATHERSTONE BADSWORTH BEAUFORT BERKELEY BICESTER BLANKNEY
BROCKLESBY CATTISTOCK CRAWLEY FITZWILLIAM GARTH GRAFTON HAYDON HOLDERNESS
LEDBURY MIDDLETON MEYNELL PUCKERIDGE PORTMAN SINNINGTON SOUTHDOWN TEDWORTH
WHADDON ALBRIGHTON CHIDDINGFOLD COTSWOLD CROOME DULVERTON EXMOOR GLAISDALE
GOATHLAND PERCY JEDFOREST LAUDERDALE BUCCLEUCH LUNESDALE ESKDALE ULLSWATER
BLENCATHRA CONISTON MELBREAK
AIRE ALN ARUN AVON CALDER COQUET DERWENT EDEN ESK EXE FROME GRETA KENNET
LEVEN LUNE MEDWAY NIDD ORWELL OUSE RIBBLE SEVERN SKERNE SWALE TAMAR TAW
TEES TEST TRENT TWEED TYNE URE WEAR WHARFE WENSUM WITHAM
CAPERCAILLIE KITTIWAKE LAPWING MERLIN OSPREY PEREGRINE PTARMIGAN SNIPE
WOODCOCK BITTERN CORNCRAKE CURLEW DOTTEREL GOSHAWK GREYLAG HERON HOBBY
KESTREL MALLARD PARTRIDGE PHEASANT PINTAIL PLOVER QUAIL REDSHANK ROOK
SHELDUCK SKYLARK SPARROWHAWK TEAL WIGEON
BARBEL BREAM CHUB DACE GRAYLING GUDGEON MINNOW PERCH PIKE ROACH RUDD SALMON
TENCH TROUT ZANDER HADDOCK HALIBUT HERRING MACKEREL PILCHARD TURBOT WHITING
BEAGLE BLOODHOUND FOXHOUND GUNDOG HARRIER LURCHER OTTERHOUND POINTER
RETRIEVER SETTER SPANIEL TERRIER WHIPPET
BLIZZARD CROSSWIND DOWNDRAFT FLURRY FOGBANK HAILSTONE HOARFROST LEVANTER
NORTHERLY SLEET SQUALL THAW THUNDERHEAD WHITEOUT ZEPHYR CLOUDBURST DOWNPOUR
FIRESTORM HAILSTORM LANDSLIDE LIGHTNING RIPTIDE WATERSPOUT WILDFIRE TEMPEST
THUNDERCLAP WHIRLWIND MAELSTROM
BULWARK CUTLASS FORTRESS JAVELIN LONGBOW PHALANX QUARTERSTAFF RAPIER VANGUARD
BAYONET BLUDGEON BROADSIDE BROADSWORD CANNONADE CROSSBOW CUDGEL DAGGER
DREADNOUGHT ESCALADE FIREBRAND FUSILLADE GRAPESHOT HAMMERHEAD IRONSIDE
JUGGERNAUT MATCHLOCK MUSKET ONSLAUGHT PICKAXE PIKESTAFF POLEAXE RAMROD
ROUNDSHOT SABRE SPEARHEAD STEAMROLLER STILETTO TREBUCHET TRIPWIRE UPPERCUT
WARHAMMER
""")
WW2_SECOND = _words("""
GARDEN HARVEST ORCHARD MEADOW FURROW HEDGEROW COPSE PADDOCK SPINNEY ACRE
BARN BYRE CROFT DAIRY DOVECOTE FALLOW FARMSTEAD FIELD FOLD GATE GRANGE GREEN
HAYRICK HEATH HOLLOW LANE LEA MANOR MARSH MILL MOOR PASTURE PENFOLD POND
QUARRY RIDGE ROOKERY SHEAF STACKYARD STILE STUBBLE THICKET TITHE WARREN
WATERMILL WEIR WINDMILL WOODLAND COMMON BRIDLEWAY CAUSEWAY
""")

EX_ADJ = _words("""
CAMBRIAN PENNINE CALEDONIAN NORTHUMBRIAN ALBION ANGLIAN ARDEN BRECON CHEVIOT
CHILTERN CORNISH COTSWOLD CUMBRIAN DARTMOOR DORSET DURHAM EXMOOR GRAMPIAN
HEBRIDEAN KENTISH LAKELAND MALVERN MENDIP MERCIAN NORFOLK ORKNEY PURBECK
QUANTOCK SALISBURY SHETLAND SNOWDON SOLWAY SUFFOLK WEALDEN WESSEX HIGHLAND
MOORLAND FENLAND COASTAL BORDER ATLANTIC
BLACK GREY GREEN WHITE AMBER ASHEN AZURE BRONZE CINDER COBALT COPPER CRIMSON
DUN EMERALD GILDED GOLDEN IVORY JADE OCHRE RUSSET SABLE SCARLET SILVER
SLATE STEEL TAWNY UMBER VERMILION GRANITE IRON
STEADFAST SILENT DISTANT SWIFT BOLD STERN VIGILANT RESOLUTE AGILE ARDENT
AUDACIOUS CONSTANT DARING DAUNTLESS DOGGED EAGER FEARLESS FERVENT FIERCE
FIRM GALLANT GRIM HARDY INTREPID KEEN LOYAL NIMBLE NOBLE PATIENT PROUD QUICK
READY RESILIENT ROBUST RUGGED SHARP SOLID STALWART STEADY STOUT STURDY
TENACIOUS TIRELESS TRUSTY UNBOWED VALIANT WARY WATCHFUL
WINTER AUTUMN SPRING SUMMER NORTHERN WESTERN EASTERN SOUTHERN MIDNIGHT
ARCTIC BOREAL DAWN DUSK FROSTY HIDDEN LUNAR MISTY NOCTURNAL POLAR SOLAR
STORMY TIDAL VERNAL TRIDENT
""")
EX_NOUN = _words("""
PATROL WARRIOR SENTINEL SHIELD STAG HAWK FALCON RAVEN HAMMER ANVIL LANCE
SABRE TRIDENT BASTION RAMPART CROSSING HORIZON TIDE STORM THUNDER VIGIL
WATCH PIKE STRIDE MARCH RIDGE CAIRN HARE FOX OTTER
ADDER BADGER BEAR BISON BOAR BUZZARD CONDOR CORMORANT CRANE EAGLE ERMINE
FERRET GANNET GRIFFIN HERON HOUND KESTREL KITE LION LYNX MARTEN MASTIFF
OSPREY OWL PANTHER POLECAT RAM SERPENT SHRIKE STOAT STALLION TIGER VIPER
WEASEL WOLF WOLVERINE WYVERN
ARROW AXE BANNER BEACON BLADE BOW BUGLE CITADEL CROWN DAGGER DRUM FLINT
FORGE GATE HALBERD HELM HORN KEEL KEEP LANTERN MACE MANTLE MUSKET OAK
PALISADE QUIVER RAPIER SCEPTRE SPEAR SPUR STANDARD STONE SWORD TORCH TOWER
ADVANCE ALLIANCE APPROACH ASSAULT BREAKOUT CHALLENGE CHARGE COVENANT
DEFENDER DESCENT ENDEAVOUR ENTERPRISE FORAY FORTUNE FRONTIER GUARDIAN
HARBOUR HUNTER JOURNEY LEGION MARATHON NAVIGATOR OUTPOST PATHFINDER PILGRIM
PROBE PURSUIT QUEST RAIDER RALLY RANGER RESOLVE RESPONSE RIDER ROVER SCOUT
SENTRY SHADOW SPIRIT STRIKE SUMMIT TEMPEST TRAIL TREK VENTURE VOYAGER
WARDEN WAVE
""")

STYLES = ("modern", "ww2", "exercise")


@dataclass
class CodeName:
    name: str        # e.g. "TELIC"
    style: str
    full: str        # e.g. "Operation TELIC"
    short: str       # e.g. "Op TELIC"


def _one(rng: random.Random, style: str) -> str:
    if style == "modern":
        return rng.choice(MODERN)
    if style == "ww2":
        if rng.random() < 0.2:
            return f"{rng.choice(WW2)} {rng.choice(WW2_SECOND)}"
        return rng.choice(WW2)
    if style == "exercise":
        return f"{rng.choice(EX_ADJ)} {rng.choice(EX_NOUN)}"
    raise ValueError(f"unknown style {style!r}; choose from {STYLES}")


def generate(style: str = "modern", count: int = 1, seed: int | None = None) -> list[CodeName]:
    """Return `count` unique code names, skipping real operation names."""
    if style not in STYLES:
        raise ValueError(f"unknown style {style!r}; choose from {STYLES}")
    rng = random.Random(seed)
    seen: set[str] = set()
    out: list[CodeName] = []
    attempts = 0
    while len(out) < count:
        attempts += 1
        if attempts > count * 200:
            raise ValueError(f"can't produce {count} unique {style} names")
        word = _one(rng, style)
        if word in REAL or word in seen:
            continue
        seen.add(word)
        kind, abbr = ("Exercise", "Ex") if style == "exercise" else ("Operation", "Op")
        out.append(CodeName(word, style, f"{kind} {word}", f"{abbr} {word}"))
    return out


def main() -> None:
    p = argparse.ArgumentParser(description="Generate British military-style code names.")
    p.add_argument("-s", "--style", choices=STYLES, default="modern")
    p.add_argument("-n", "--count", type=int, default=5)
    p.add_argument("--seed", type=int)
    a = p.parse_args()
    for c in generate(a.style, a.count, a.seed):
        print(c.full)


if __name__ == "__main__":
    main()
